### ISSUE TITLE
3.1.0 broke my nova 4 views

### ISSUE THREAD

**Issue by mstaack** [appstract/nova-horizon#14]
latest version broke our nova view,
probably some css classes are wrongly applied

**Comment by gizburdt** [comment]
The `important: .nova-horizon` property is removed in 3.1.0 which causes this problem. But when I enable this again, dark mode will not work. Any ideas?

**Comment by macbookandrew** [comment]
Yeah, I removed that because it broke the automatic light/dark mode Nova switcher, and I didn’t see anything breaking without it.

Do you have any screenshots of what breaks?

**Comment by gizburdt** [comment]
I was able to reproduce this.

<img width="993" alt="image" src="https://user-images.githubusercontent.com/1470623/224355577-5edf87f7-dbeb-4c3d-9dde-27d365f35f27.png">

**Comment by macbookandrew** [comment]
Looks like it’s due to the order stylesheets are loaded:

![priority rules](https://user-images.githubusercontent.com/784333/224357817-4d4223d9-84f2-482d-a005-210faee25069.png)

**Comment by macbookandrew** [comment]
Seems like the only way to fix this is to use the [prefix option](https://tailwindcss.com/docs/configuration#prefix) and prefix all the classes used in this package…

I haven’t found any way to combine the [important selector strategy](https://tailwindcss.com/docs/configuration#selector-strategy) with [manual dark mode](https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually) to get the classes to work correctly.

What we need:

```css

.dark .nova-horizon .dark\:border-gray-700 {
  --tw-border-opacity: 1;
  border-color: rgb(55 65 81 / var(--tw-border-opacity));
}
```

What we get:

```css

.nova-horizon .dark .dark\:border-gray-700 {
  --tw-border-opacity: 1;
  border-color: rgb(55 65 81 / var(--tw-border-opacity));
}
```
